[package]
name = "module_path_extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0"
proc-macro2 = { version = "1.0", features = [] }

[dependencies.syn]
features = ["full", "visit-mut", "visit"]
version = "2.0"
